apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: observability
spec:
  mode: deployment
  managementState: managed
  image: otel/opentelemetry-collector-contrib:0.152.0
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      transform:
        trace_statements:
          - context: resource
            statements:
              - set(attributes["service.name"], Concat([attributes["k8s.namespace.name"], attributes["service.name"]], "/"))
    exporters:
      debug:
        verbosity: detailed
      otlp/jaeger:
        endpoint: jaeger.observability.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [transform]
          exporters: [debug, otlp/jaeger]
